Import('env')

helper = env.Substfile('driver.py.in', SUBST_DICT={'@LLVM_BINDIR@': env.subst('$LLVM_bindir')})
Default(helper)

driver = env.Substfile('#Release/csi-cc',
                       'csi-driver.py.in',
                       SUBST_DICT={"@USE_GAMS@": str("GAMSDIR" in env),
                                   "@GAMS_INSTALL_DIR@": env.get("GAMSDIR", "")})
AddPostAction(driver, Chmod('$TARGET', 0755))
